version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=express-ts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./src:/app/src
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   environment:
  #     - POSTGRES_DB=express-ts
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_HOST=db

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile # or Dockerfile.dev if you have a development Dockerfile for the frontend
  #   volumes:
  #     - ./frontend/src:/app/src
  #     - /app/src/node_modules
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - app
